const String tmpl_index = "<!doctype html>"
                          "<html>"
                          "<head>"
                          "<title>Auto Car Webserver</title>"
                          "</head>"
                          "<body>"
                          "<h1>Auto Car</h1>"
                          "<form action='' method='GET'>LED 1:"
                          "<input type='radio' name='led1' value='L1on' /> LED ON<br/>"
                          "<input type='radio' name='led1' value='L1off' /> LED OFF<br/>"
                          "LED 2:"
                          "<input type='radio' name='led2' value='L2on' /> LED ON<br/>"
                          "<input type='radio' name='led2' value='L2off' /> LED OFF<br/>"
                          "<input type='submit' value='Submit' />"
                          "</form>"
                          "</body>"
                          "</html>";
